//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grievancemis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Grievance_DBEntities : DbContext
    {
        public Grievance_DBEntities()
            : base("name=Grievance_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<m_State_Master> m_State_Master { get; set; }
        public virtual DbSet<Tbl_Grievance> Tbl_Grievance { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<M_GrievanceType> M_GrievanceType { get; set; }
    
        public virtual ObjectResult<USP_GetGrievanceList_Result> USP_GetGrievanceList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetGrievanceList_Result>("USP_GetGrievanceList");
        }
    }
}
