//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grievancemis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoginVerification
    {
        public System.Guid Id { get; set; }
        public int IntId { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Issent { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<bool> IsValidEmailId { get; set; }
        public Nullable<System.DateTime> VerificationCodeOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Resend { get; set; }
        public Nullable<System.DateTime> ResendDt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ExpiryAt { get; set; }
    }
}
