//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grievancemis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TeamRevertComplain
    {
        public int TeamId_pk { get; set; }
        public System.Guid GrievanceId_fk { get; set; }
        public Nullable<int> RevertTypeId { get; set; }
        public string TeamRevertMessage { get; set; }
        public Nullable<int> TeamRoleId { get; set; }
        public Nullable<System.DateTime> TeamRevert_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> TeamIsSent { get; set; }
        public Nullable<System.DateTime> TeamIsSentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UserRevertId { get; set; }
        public string UserRevertMessage { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<System.DateTime> UserRevert_Date { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> UserIsSentDate { get; set; }
        public Nullable<bool> UserIsSent { get; set; }
        public Nullable<int> RevertDuration { get; set; }
        public Nullable<bool> IsSentMailRevertDuration { get; set; }
        public Nullable<System.DateTime> SentMailRevertDuration { get; set; }
        public Nullable<int> Revertcb_value { get; set; }
    
        public virtual Tbl_Grievance Tbl_Grievance { get; set; }
    }
}
