//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grievancemis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Grievance
    {
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> GrievanceType { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Issent { get; set; }
        public string Title { get; set; }
        public string Grievance_Message { get; set; }
        public Nullable<bool> IsConsent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
    }
}
