//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grievancemis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoginVerification
    {
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Issent { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<long> Timeminutes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsValidEmailId { get; set; }
    }
}
